export const S = {
  conversations: [],
  activeConvId: null,
  activeCharId: null,
  messages: [],
  fragments: [],
  characters: [],
  settings: {},
  directorState: null,
  lastDirectorData: null,
  isStreaming: false,
  streamingBodyEl: null,
  streamCutoffIndex: null,
  agentEnabled: true,
  enabledTools: { direct_scene: true, rewrite_user_prompt: false, refine_apply_patch: false },
  editingMsgId: null,
  abortController: null,
  streamingContent: null,
  pendingUserMsg: null,
  wasAborted: false,
  _selectCharLock: false,
  generationPhase: null,
};