"""Backend database package.

Re-exports the public API previously provided by the monolithic
backend/database.py module so existing call sites keep working.
"""

from __future__ import annotations

from .bootstrap import init_db, reset_to_defaults
from .connection import DB_PATH, get_db
from .queries.character_cards import (
    create_character_card,
    delete_character_card,
    get_character_avatar,
    get_character_card,
    get_workflow_character_state,
    insert_alternate_greeting_swipes,
    list_character_cards,
    resolve_char_context,
    set_workflow_character_state,
    sync_conversations_for_card,
    update_character_card,
)
from .queries.conversation_logs import (
    add_conversation_log,
    get_conversation_logs,
    get_director_log_for_message,
    get_moods_before_turn,
)
from .queries.conversations import (
    create_conversation,
    delete_conversation,
    fork_conversation,
    get_conversation,
    get_workflow_state,
    list_conversations,
    set_workflow_state,
    touch_conversation,
    update_conversation,
)
from .queries.interactive_fragments import (
    create_interactive_fragment,
    delete_interactive_fragment,
    get_interactive_fragment,
    get_interactive_fragments,
    update_interactive_fragment,
)
from .queries.director_state import get_director_state, update_director_state
from .queries.endpoints import (
    create_endpoint,
    create_model_config,
    delete_endpoint,
    delete_model_config,
    get_endpoint,
    get_endpoints,
    get_model_configs,
    update_endpoint,
    update_model_config,
)
from .queries.messages import (
    add_message,
    delete_message_with_descendants,
    get_deepest_descendant,
    get_message_by_id,
    get_messages,
    get_messages_before,
    get_messages_with_branch_info,
    get_path_to_leaf,
    get_user_attachments_for_message,
    get_workflow_attachments_for_message,
    get_workflow_message_state,
    set_active_leaf,
    set_workflow_message_state,
    switch_to_branch,
    update_message_content,
    user_attachment_payloads,
)
from .queries.workflow_attachments import (
    get_workflow_attachment_by_id,
    insert_workflow_attachment_row,
)
from .queries.mood_fragments import (
    create_mood_fragment,
    delete_mood_fragment,
    get_mood_fragment,
    get_mood_fragments,
    update_mood_fragment,
)
from .queries.phrase_bank import (
    add_phrase_group,
    delete_phrase_group,
    get_phrase_bank,
    get_phrase_bank_rows,
    update_phrase_group,
)
from .queries.settings import (
    get_settings,
    get_workflow_config,
    set_workflow_config,
    update_settings,
)
from .queries.user_personas import (
    create_user_persona,
    delete_user_persona,
    get_user_persona,
    get_user_personas,
    update_user_persona,
)
from .queries.worlds import (
    create_lorebook_entry,
    create_world,
    delete_lorebook_entry,
    delete_world,
    get_active_lorebook_entries,
    get_lorebook_entries,
    get_lorebook_entry,
    get_world,
    get_world_by_name,
    get_worlds,
    update_lorebook_entry,
    update_world,
)
from .seeds import (
    DEFAULT_ENABLED_TOOLS,
    DEFAULT_SETTINGS,
    SEED_INTERACTIVE_FRAGMENTS,
    SEED_MOOD_FRAGMENTS,
    SEED_PHRASE_BANK,
)

__all__ = [
    "DB_PATH",
    "DEFAULT_ENABLED_TOOLS",
    "DEFAULT_SETTINGS",
    "SEED_INTERACTIVE_FRAGMENTS",
    "SEED_MOOD_FRAGMENTS",
    "SEED_PHRASE_BANK",
    "add_conversation_log",
    "add_message",
    "add_phrase_group",
    "create_character_card",
    "create_conversation",
    "create_interactive_fragment",
    "create_endpoint",
    "create_lorebook_entry",
    "create_model_config",
    "create_mood_fragment",
    "create_user_persona",
    "create_world",
    "delete_character_card",
    "delete_conversation",
    "delete_interactive_fragment",
    "delete_endpoint",
    "delete_lorebook_entry",
    "delete_message_with_descendants",
    "delete_model_config",
    "delete_mood_fragment",
    "delete_phrase_group",
    "delete_user_persona",
    "delete_world",
    "fork_conversation",
    "get_active_lorebook_entries",
    "get_character_avatar",
    "get_character_card",
    "get_conversation",
    "get_conversation_logs",
    "get_db",
    "get_deepest_descendant",
    "get_interactive_fragment",
    "get_interactive_fragments",
    "get_director_log_for_message",
    "get_director_state",
    "get_endpoint",
    "get_endpoints",
    "get_lorebook_entries",
    "get_lorebook_entry",
    "get_message_by_id",
    "get_messages",
    "get_messages_before",
    "get_messages_with_branch_info",
    "get_model_configs",
    "get_mood_fragment",
    "get_mood_fragments",
    "get_moods_before_turn",
    "get_path_to_leaf",
    "get_phrase_bank",
    "get_phrase_bank_rows",
    "get_settings",
    "get_user_attachments_for_message",
    "get_user_persona",
    "get_user_personas",
    "get_workflow_attachment_by_id",
    "get_workflow_attachments_for_message",
    "get_workflow_character_state",
    "get_workflow_config",
    "get_workflow_message_state",
    "get_workflow_state",
    "get_world",
    "get_world_by_name",
    "get_worlds",
    "init_db",
    "insert_alternate_greeting_swipes",
    "insert_workflow_attachment_row",
    "list_character_cards",
    "list_conversations",
    "reset_to_defaults",
    "resolve_char_context",
    "set_active_leaf",
    "set_workflow_character_state",
    "set_workflow_config",
    "set_workflow_message_state",
    "set_workflow_state",
    "switch_to_branch",
    "sync_conversations_for_card",
    "touch_conversation",
    "update_character_card",
    "update_conversation",
    "update_interactive_fragment",
    "update_director_state",
    "update_endpoint",
    "update_lorebook_entry",
    "update_message_content",
    "update_model_config",
    "update_mood_fragment",
    "update_phrase_group",
    "update_settings",
    "update_user_persona",
    "update_world",
    "user_attachment_payloads",
]
