"""Tests for Spark-TTS enrollment with the real speaker encoder."""

from __future__ import annotations

import os

import pytest

np = pytest.importorskip("numpy")
pytest.importorskip("onnxruntime")

from backend.inference.local_models.spark_tts import (  # noqa: E402
    audio_in,
    catalog,
    enroll,
    tokens,
)

# Use the real model directory when the optional artifact is available.
pytestmark = [
    pytest.mark.real_model_dir,
    pytest.mark.skipif(
        not os.path.exists(catalog.speaker_encoder_path()),
        reason="speaker encoder not downloaded (scripts/export_spark_speaker_encoder.py)",
    ),
]

#: Reference tokens generated by the upstream speaker encoder.
_PROMPT_AUDIO_TOKENS = [
    3363, 2367, 1591, 3625, 294, 3556, 1198, 2646,
    3397, 3778, 2459, 3109, 1017, 3860, 3178, 3414,
    1727, 561, 1096, 3133, 3647, 3178, 2767, 73,
    2418, 1838, 3645, 2338, 3451, 2144, 306, 2799,
]  # fmt: skip

_REFERENCE_WAV = os.path.join(
    os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))),
    "..",
    "OrbTTS",
    "vendor",
    "Spark-TTS",
    "example",
    "prompt_audio.wav",
)


def test_enrollment_shape_and_range():
    """Enrollment returns 32 in-range codes for each signal."""
    for signal in (
        np.zeros(96000, dtype=np.float32),
        (np.random.default_rng(0).standard_normal(96000) * 0.1).astype(np.float32),
        np.ones(1000, dtype=np.float32) * 0.2,  # shorter than the window; tiled
    ):
        got = enroll.enroll_signal(enroll.reference_clip(signal))
        assert tokens.validate_speaker_tokens(got) == got


def test_enrollment_is_deterministic():
    """The same signal produces the same speaker tokens."""
    signal = (np.random.default_rng(3).standard_normal(96000) * 0.1).astype(np.float32)
    assert enroll.enroll_signal(enroll.reference_clip(signal)) == enroll.enroll_signal(enroll.reference_clip(signal))


def test_different_signals_enroll_differently():
    """Different signals produce different speaker tokens."""
    rng = np.random.default_rng(11)
    a = enroll.enroll_signal(enroll.reference_clip(rng.standard_normal(96000).astype(np.float32) * 0.1))
    b = enroll.enroll_signal(enroll.reference_clip(np.zeros(96000, dtype=np.float32)))
    assert a != b


@pytest.mark.skipif(not os.path.exists(_REFERENCE_WAV), reason="upstream reference clip not checked out")
def test_reproduces_the_torch_reference():
    """The NumPy and ONNX path matches the upstream reference tokens."""
    with open(_REFERENCE_WAV, "rb") as handle:
        data = handle.read()
    # Compare the same six-second reference segment as the fixture.
    signal = enroll.reference_clip(audio_in.decode(data, filename="prompt_audio.wav"), trim=False)
    assert enroll.enroll_signal(signal[:96000]) == _PROMPT_AUDIO_TOKENS


def test_a_long_clip_is_enrolled_past_its_first_six_seconds():
    """Speech after six seconds contributes to enrollment."""
    rng = np.random.default_rng(5)
    head = (rng.standard_normal(96000) * 0.1).astype(np.float32)
    tail = np.sin(np.arange(20 * 16000) * 2 * np.pi * 220 / 16000).astype(np.float32) * 0.3
    only_head = enroll.enroll_signal(enroll.reference_clip(head))
    assert enroll.enroll_signal(enroll.reference_clip(np.concatenate([head, tail]))) != only_head
